# Generated by Django 4.0.4 on 2022-04-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('notice_number', models.TextField(primary_key=True, serialize=False)),
                ('notice_date', models.TextField(blank=True, null=True)),
                ('tender_name', models.TextField(blank=True, null=True)),
                ('procedure_state', models.TextField(blank=True, null=True)),
                ('contract_type', models.TextField(blank=True, null=True)),
                ('procedure_type', models.TextField(blank=True, null=True)),
                ('estimated_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notices',
                'managed': False,
            },
        ),
    ]
